---
language: python

python:
  - '2.7'

install:
  - pip install -q -r requirements-dev.txt .

script:
  - coverage run --source housekeeper setup.py test

after_success: coveralls

notifications:
  email: false
  slack:
    secure: xjtJOKsJolsv/dtDgxG742XN8l9RGVbW9gLMG6aiPqXl2j273SJd4dQeG+bU66hD+XlsBa7pfNx/KQUw6AECCIZyM4AbNhckKihgkFJbjM+iyqzMry6y4qZjsY34I2T9hwPlOtL9/pz3PcmH/oz1XNOaEjggcCJ1it1f5Lksqz/qx6iSra7WSaIxxYl1PYMS2eBDNNz/7o4okZdz8tmTOVbum9PaPI9bZDZ9QPnWXD4iaOEBVnhGmGaKVHW1jJ8D30Lfjq4rVBXsQ/W+bh8SqXVMT4RTJ1RVcLVzfBhhrIOtP5GY8I8E64FSCZno6iEaMxRoxEk4heKmtwFW/egbIld1gfqyOkZmTjS0UN19r1HDeOjW/J3vFXtBOw9VrUbraoD6TmzaWzrdBwBq2zwtDZVzWqD+v+D0I3ybSIUv/9H8dHL3oyDPUYRO8f54uM3GkJtbgCtZppuuzswmbLXSOVQ3ZL3dg0IgV4D2udVeiJxz2Zf3G/IAzhPFUy/Xzofg8q01Cycoa9907Gb/Jwk+I0rp0d5QwiSCoyDkOksIs1Kbe3i2q4ijNKhcrVDan+5jDUcBHy3Now3tn/yH18/iwigiSrfiKdBONE2GRVMYMGXz44hax9tE+HKnVWEdkXJC3onRdqbzhV3u8AaRoO+BM7FYo9CUMQ/zUV1bZZ/Zefk=

deploy:
  provider: pypi
  user: robinandeer
  password:
    secure: UkXbhDi1Y+GhgUVxt3qEH3zVppS0rbtzRWUTGd13/nIJUcwELAe16gIaIVgGwJK/OVrGMAFfoCpC3By+5cKXhmIyPlVKf7PjHC1QD3koJ0Rlgb04JeMt0yfb5ve16l5Tp/pr4rTKmGq+RFMziHen7m2Hc344k+ruvi0gYcwxPvPTZG6KnJwjn5tz/HylQgcQFsUR8QJD/Zut1ysa5H9iVa0nrUa/7YzMgHUHX4GM+TzCOuo4Q4eNsYcgu3Ntp0wygQT4+/JAfUoOkOqmTK31O9itGnRhylmmfri7gshuxEDsLllRbxSUu99Fj5kHZKcp+BCE/fvmmAokmnhyfnOaHiOszISEUMqD3ZvSzrMuO3RYT4CTEUtOND2eDzdTDrUB6HQ9UJw+QcOTvpEN7q2oZWy5/Ohgj3hmsxS+tJG7PAmZPWYrLkF8qsTxqxB0Fu1fbhJUT5o1gBkVzPT9h5YthjFa79Wz1gBmAKWlohKPPSVjoEdw0+RPzj7h8quhBhtNXUFLg0Vr8y+XSjwjt1QSr/BlcEAbeumoDDLRFD/evp6NzcttBiIgqZE0OXxXY8O77cwad4ME98qeRNyrI+x+IR/l5ZiIub2NsSeZqdZ7eKC2OMVbJDqpqMEmFUT4SasxtK4uKiCOcE9sTLTIM0U9/0amtgXiYAgpQhwuLnDLvPc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Clinical-Genomics/housekeeper
