"""add is started field for cases

Revision ID: 0411d9eb8b9f
Revises: f6b2c1186ec5
Create Date: 2017-05-15 15:14:21.090145

"""

# revision identifiers, used by Alembic.
revision = '0411d9eb8b9f'
down_revision = 'f6b2c1186ec5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('is_started', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'is_started')
    ### end Alembic commands ###
