"""add cleanup date tracker

Revision ID: 17085dda2b9d
Revises: d0eab2dee85a
Create Date: 2016-09-13 11:21:58.415800

"""

# revision identifiers, used by Alembic.
revision = '17085dda2b9d'
down_revision = 'd0eab2dee85a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('will_cleanup_at', sa.Date(), nullable=True))
    op.drop_column('analysis', 'will_archive_at')
    op.add_column('analysis_run', sa.Column('cleanedup_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_run', 'cleanedup_at')
    op.add_column('analysis', sa.Column('will_archive_at', mysql.DATETIME(), nullable=True))
    op.drop_column('analysis', 'will_cleanup_at')
    ### end Alembic commands ###
