"""add reference genome to analysis run

Revision ID: 43018c296295
Revises: b2893331b4d2
Create Date: 2017-02-14 09:07:53.132798

"""

# revision identifiers, used by Alembic.
revision = '43018c296295'
down_revision = 'b2893331b4d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_run', sa.Column('reference_genome', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_run', 'reference_genome')
    ### end Alembic commands ###
