"""add data archive paths

Revision ID: 7ab7ab3d4f6e
Revises: d24304894201
Create Date: 2016-09-13 23:02:04.327546

"""

# revision identifiers, used by Alembic.
revision = '7ab7ab3d4f6e'
down_revision = 'd24304894201'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_run', sa.Column('data_archive', sa.String(length=256), nullable=True))
    op.add_column('analysis_run', sa.Column('result_archive', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_run', 'result_archive')
    op.drop_column('analysis_run', 'data_archive')
    ### end Alembic commands ###
