"""add rerun requested field to case

Revision ID: 9334201fec74
Revises: eada86aa0b22
Create Date: 2017-05-23 14:49:10.947685

"""

# revision identifiers, used by Alembic.
revision = "9334201fec74"
down_revision = "eada86aa0b22"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("rerun_requested", sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case", "rerun_requested")
    ### end Alembic commands ###
