"""add mark for cases on hold

Revision ID: ac9547bfbf42
Revises: 619fe6fe066c
Create Date: 2017-04-28 11:14:19.232902

"""

# revision identifiers, used by Alembic.
revision = 'ac9547bfbf42'
down_revision = '619fe6fe066c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('is_onhold', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'is_onhold')
    ### end Alembic commands ###
