"""add list of flowcells to sample

Revision ID: b2893331b4d2
Revises: 2f5352038e54
Create Date: 2017-02-09 13:34:42.653090

"""

# revision identifiers, used by Alembic.
revision = 'b2893331b4d2'
down_revision = '2f5352038e54'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('_flowcells', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', '_flowcells')
    ### end Alembic commands ###
