"""remove status, make datetime -> date

Revision ID: d0eab2dee85a
Revises: eff3a487aa92
Create Date: 2016-09-12 16:00:31.007388

"""

# revision identifiers, used by Alembic.
revision = 'd0eab2dee85a'
down_revision = 'eff3a487aa92'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_run', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_run', sa.Column('status', mysql.ENUM(u'active', u'archived'), nullable=True))
    ### end Alembic commands ###
