"""make clean up field DateTime

Revision ID: d1b57526951f
Revises: 17085dda2b9d
Create Date: 2016-09-13 13:28:59.804431

"""

# revision identifiers, used by Alembic.
revision = 'd1b57526951f'
down_revision = '17085dda2b9d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
