"""initial structure

Revision ID: d24304894201
Revises: 
Create Date: 2016-09-13 18:45:06.579220

"""

# revision identifiers, used by Alembic.
revision = 'd24304894201'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
