"""add link between sample and run

Revision ID: e342985be691
Revises: 1b0a755720b2
Create Date: 2016-12-20 15:47:57.498932

"""

# revision identifiers, used by Alembic.
revision = 'e342985be691'
down_revision = '1b0a755720b2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_run_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'run_id', name='_sample_run_uc')
    )
    op.create_foreign_key(None, 'asset', 'analysis_run', ['run_id'], ['id'])
    op.create_foreign_key(None, 'asset', 'sample', ['sample_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_table('sample_run_link')
    ### end Alembic commands ###
