"""initial structure

Revision ID: e5d3b6f4e074
Revises: 
Create Date: 2016-11-09 14:59:09.033966

"""

# revision identifiers, used by Alembic.
revision = 'e5d3b6f4e074'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
