"""add is manual field to case

Revision ID: eada86aa0b22
Revises: 0411d9eb8b9f
Create Date: 2017-05-15 15:42:45.804169

"""

# revision identifiers, used by Alembic.
revision = 'eada86aa0b22'
down_revision = '0411d9eb8b9f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('is_manual', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'is_manual')
    ### end Alembic commands ###
