"""empty message Creates a new table describing archiving and retrieval tasks

Revision ID: f1669dd42064
Revises: 9334201fec74
Create Date: 2023-04-21 10:46:22.396771

"""

# revision identifiers, used by Alembic.
revision = 'f1669dd42064'
down_revision = '9334201fec74'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('archiving_task_id', sa.Integer(), nullable=False),
    sa.Column('retrieval_task_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive')
    # ### end Alembic commands ###
