"""add category field on sample

Revision ID: f6b2c1186ec5
Revises: cd9166dd20cf
Create Date: 2017-05-10 14:05:26.285514

"""

# revision identifiers, used by Alembic.
revision = "f6b2c1186ec5"
down_revision = "cd9166dd20cf"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sample",
        sa.Column(
            "category",
            sa.Enum("wgs", "wes", "tga", "wgs-ext", "wes-ext", "tga-ext"),
            nullable=True,
        ),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sample", "category")
    ### end Alembic commands ###
