name: Black

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: psf/black@stable
        with:
          options: ". --check --line-length 100"
