name: Publish to PyPI and Docker

on:
  release:
    types:
      - created

jobs:
  build-n-publish:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2.6.0

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Publish Distribution to PyPI 📦
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          poetry publish --no-interaction --build \
            --username $PYPI_USERNAME \
            --password $PYPI_PASSWORD

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.6.0
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: clinicalgenomics/housekeeper
          tag_with_ref: true
