name: Housekeeper installation and linting

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:

    # Check out Housekeeper code
    - uses: actions/checkout@v2.6.0

    # Set up python
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v4.3.1
      with:
        python-version: ${{ matrix.python-version}}

    - name: Production Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip check

    - name: Development Dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install flake8
        pip check

    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      # Let linters fix problems if they can
      with:
        github_token: ${{ secrets.github_token }}
        auto_fix: true
        # Enable linters
        # stop the build if there are Python syntax errors or undefined names
        flake8: true
        flake8_args: "housekeeper/ --count --select=E9,F63,F7,F82 --show-source --statistics"
