name: Housekeeper installation and linting

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2.6.0

    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v4.3.1
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false

    - name: Production and Development Dependencies
      run: |
        poetry install
        poetry check

    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        auto_fix: true
        flake8: true
        flake8_args: "housekeeper/ --count --select=E9,F63,F7,F82 --show-source --statistics"
